package live.turna.phenyl.message.schema;

/**
 * Generated by <a href="https://json2csharp.com/xml-to-java/">json2csharp</a> for QQ XML card messages.
 */
public class TencentXMLMessage {
    public static class picture {
        public String cover;
        public int w;
        public int h;
    }

    public static class item {
        public picture picture;
        public String title;
        public String summary;
        public int layout;
        public int advertiser_id;
        public int aid;
        public String text;
    }

    public static class source {
        public String name;
        public String icon;
        public String url;
        public String action;
        public String a_actionData;
        public int appid;
    }

    public static class msg {
        public item item;
        public source source;
        public int serviceID;
        public int templateID;
        public String action;
        public String brief;
        public int sourceMsgId;
        public String url;
        public int flag;
        public int adverSign;
        public int multiMsgFlag;
        public String text;
    }
}