package live.turna.phenyl.common.message.schema;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by <a href="https://www.jsonschema2pojo.org/">jsonschema2pojo</a> for QQ card messages which doesn't match any known pattern.
 */
public class GroupCardFallbackMessage {
    @SerializedName("app")
    @Expose
    public String app;
    @SerializedName("desc")
    @Expose
    public String desc;
    @SerializedName("view")
    @Expose
    public String view;
    @SerializedName("ver")
    @Expose
    public String ver;
    @SerializedName("prompt")
    @Expose
    public String prompt;
    @SerializedName("meta")
    @Expose
    public Meta meta;
    @SerializedName("config")
    @Expose
    public Config config;

    public class Config {
    }

    public class Meta {
    }
}