package live.turna.phenyl.common.message.schema;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by <a href="https://www.jsonschema2pojo.org/">jsonschema2pojo</a> for QQ announcements.
 */
public class GroupAnnounceMessage {

    @SerializedName("app")
    @Expose
    public String app;
    @SerializedName("config")
    @Expose
    public Config config;
    @SerializedName("desc")
    @Expose
    public String desc;
    @SerializedName("extra")
    @Expose
    public Extra extra;
    @SerializedName("meta")
    @Expose
    public Meta meta;
    @SerializedName("prompt")
    @Expose
    public String prompt;
    @SerializedName("ver")
    @Expose
    public String ver;
    @SerializedName("view")
    @Expose
    public String view;

    public class Mannounce {

        @SerializedName("cr")
        @Expose
        public Integer cr;
        @SerializedName("encode")
        @Expose
        public Integer encode;
        @SerializedName("fid")
        @Expose
        public String fid;
        @SerializedName("gc")
        @Expose
        public String gc;
        @SerializedName("sign")
        @Expose
        public String sign;
        @SerializedName("text")
        @Expose
        public String text;
        @SerializedName("title")
        @Expose
        public String title;
        @SerializedName("tw")
        @Expose
        public Integer tw;
        @SerializedName("uin")
        @Expose
        public String uin;
    }

    public class Meta {

        @SerializedName("mannounce")
        @Expose
        public Mannounce mannounce;

    }

    public class Config {

        @SerializedName("ctime")
        @Expose
        public Integer ctime;
        @SerializedName("forward")
        @Expose
        public Integer forward;
        @SerializedName("token")
        @Expose
        public String token;

    }

    public class Extra {

        @SerializedName("app_type")
        @Expose
        public Integer appType;
        @SerializedName("appid")
        @Expose
        public Integer appid;
        @SerializedName("uin")
        @Expose
        public Integer uin;

    }
}

